# Generated by Django 4.0.4 on 2022-07-25 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baojiadan',
            fields=[
                ('quoteid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tcount', models.FloatField(blank=True, null=True)),
                ('quote', models.FloatField(blank=True, null=True)),
                ('validitytime', models.DateTimeField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('isreceived', models.IntegerField(blank=True, choices=[(0, '待评估'), (1, '接受'), (2, '拒绝'), (3, '已完成')], null=True)),
                ('isdelete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'baojiadan',
            },
        ),
        migrations.CreateModel(
            name='Caigoudan',
            fields=[
                ('purchaseid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('tcount', models.FloatField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('iscomplete', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True)),
                ('isdelete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'caigoudan',
            },
        ),
        migrations.CreateModel(
            name='Caigouxuqiu',
            fields=[
                ('demandid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('tcount', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, '未审核'), (1, '已审核'), (2, '已完成')], null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('verifytime', models.DateTimeField(blank=True, null=True)),
                ('isdelete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'caigouxuqiu',
            },
        ),
        migrations.CreateModel(
            name='Gongchang',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gongchang',
            },
        ),
        migrations.CreateModel(
            name='Gongsi',
            fields=[
                ('myid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('postcode', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('telephone', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'gongsi',
            },
        ),
        migrations.CreateModel(
            name='Gongyingshang',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gongyingshang',
            },
        ),
        migrations.CreateModel(
            name='Wuliao',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('salegroup', models.CharField(blank=True, max_length=40, null=True)),
                ('saleway', models.CharField(blank=True, max_length=40, null=True)),
                ('calcutype', models.CharField(blank=True, max_length=10, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wuliao',
            },
        ),
        migrations.CreateModel(
            name='Zanshoudan',
            fields=[
                ('temid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tcount', models.FloatField(blank=True, null=True)),
                ('qualitycheckinfo', models.IntegerField(blank=True, choices=[(1, '通过'), (0, '不通过'), (-1, '未检查')], null=True)),
                ('quantitycheckinfo', models.IntegerField(blank=True, choices=[(1, '通过'), (0, '不通过'), (-1, '未检查')], null=True)),
                ('isreceived', models.IntegerField(blank=True, choices=[(1, '已入库'), (0, '未入库'), (2, '已入库')], null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('isdelete', models.IntegerField(default=0)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao')),
                ('purchaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.caigoudan')),
            ],
            options={
                'db_table': 'zanshoudan',
            },
        ),
        migrations.CreateModel(
            name='Yuangong',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('isactive', models.IntegerField(blank=True, choices=[(1, '启用'), (0, '禁用')], null=True)),
                ('issuper', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True)),
                ('businessid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongsi')),
            ],
            options={
                'db_table': 'yuangong',
            },
        ),
        migrations.CreateModel(
            name='Xunjiadan',
            fields=[
                ('inquiryid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tcount', models.FloatField(blank=True, null=True)),
                ('validitytime', models.DateTimeField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('isdelete', models.IntegerField(default=0)),
                ('bussid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongsi')),
                ('createuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.yuangong')),
                ('demandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.caigouxuqiu')),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao')),
                ('supplyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongyingshang')),
            ],
            options={
                'db_table': 'xunjiadan',
            },
        ),
        migrations.CreateModel(
            name='Xiaoxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('read', models.IntegerField(choices=[(1, '已读'), (0, '未读')], default=0)),
                ('fromId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='supply.yuangong')),
                ('toId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='supply.yuangong')),
            ],
        ),
        migrations.CreateModel(
            name='Tuihuodan',
            fields=[
                ('rejectedid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tcount', models.FloatField(blank=True, null=True)),
                ('reason', models.IntegerField(blank=True, choices=[(1, '质检不合格'), (2, '运输过程破损'), (3, '额外产品'), (4, '其他')], null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('isdelete', models.IntegerField(default=0)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao')),
                ('temid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.zanshoudan')),
            ],
            options={
                'db_table': 'tuihuodan',
            },
        ),
        migrations.CreateModel(
            name='Rukudan',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('receivecount', models.FloatField(blank=True, null=True)),
                ('purcount', models.FloatField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('isdelete', models.IntegerField(default=0)),
                ('createusersid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updateusersid', to='supply.yuangong')),
                ('facid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongchang')),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao')),
                ('temid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.zanshoudan')),
            ],
            options={
                'db_table': 'rukudan',
            },
        ),
        migrations.AddField(
            model_name='gongyingshang',
            name='createnumberid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updatenumberid', to='supply.yuangong'),
        ),
        migrations.AddField(
            model_name='gongyingshang',
            name='updatenumberid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createnumberid', to='supply.yuangong'),
        ),
        migrations.CreateModel(
            name='Gongyingguanxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
                ('createid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updateid', to='supply.yuangong')),
                ('materialid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao')),
                ('supplyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongyingshang')),
                ('updateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createid', to='supply.yuangong')),
            ],
            options={
                'db_table': 'gongyingguanxi',
            },
        ),
        migrations.CreateModel(
            name='Gongchangkucun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventoryonroad', models.FloatField(blank=True, null=True)),
                ('inventorytemp', models.FloatField(blank=True, null=True)),
                ('inventoryunrest', models.FloatField(blank=True, null=True)),
                ('inventoryfreeze', models.FloatField(blank=True, null=True)),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
                ('facid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongchang')),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao')),
            ],
            options={
                'db_table': 'gongchangkucun',
            },
        ),
        migrations.CreateModel(
            name='Fapiao',
            fields=[
                ('invoiceid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('money', models.FloatField(blank=True, null=True)),
                ('totalcount', models.FloatField(blank=True, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('totalmoney', models.FloatField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('moreinfo', models.CharField(blank=True, max_length=255, null=True)),
                ('isdelete', models.IntegerField(default=0)),
                ('createuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.yuangong')),
                ('purchaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.caigoudan')),
                ('supplyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongyingshang')),
            ],
            options={
                'db_table': 'fapiao',
            },
        ),
        migrations.AddField(
            model_name='caigouxuqiu',
            name='createuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifyuserid', to='supply.yuangong'),
        ),
        migrations.AddField(
            model_name='caigouxuqiu',
            name='facid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongchang'),
        ),
        migrations.AddField(
            model_name='caigouxuqiu',
            name='maid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao'),
        ),
        migrations.AddField(
            model_name='caigouxuqiu',
            name='verifyuserid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createuserid', to='supply.yuangong'),
        ),
        migrations.AddField(
            model_name='caigoudan',
            name='createuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.yuangong'),
        ),
        migrations.AddField(
            model_name='caigoudan',
            name='facid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongchang'),
        ),
        migrations.AddField(
            model_name='caigoudan',
            name='maid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao'),
        ),
        migrations.AddField(
            model_name='caigoudan',
            name='quoteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.baojiadan'),
        ),
        migrations.AddField(
            model_name='caigoudan',
            name='supplyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongyingshang'),
        ),
        migrations.CreateModel(
            name='Buhuodan',
            fields=[
                ('repleid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tcount', models.FloatField(blank=True, null=True)),
                ('isnewpur', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True)),
                ('isdelete', models.IntegerField(default=0)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao')),
                ('temid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.zanshoudan')),
            ],
            options={
                'db_table': 'buhuodan',
            },
        ),
        migrations.AddField(
            model_name='baojiadan',
            name='bussid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongsi'),
        ),
        migrations.AddField(
            model_name='baojiadan',
            name='createuserid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.yuangong'),
        ),
        migrations.AddField(
            model_name='baojiadan',
            name='inquiryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.xunjiadan'),
        ),
        migrations.AddField(
            model_name='baojiadan',
            name='maid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.wuliao'),
        ),
        migrations.AddField(
            model_name='baojiadan',
            name='supplyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.gongyingshang'),
        ),
    ]
